name: Python package

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
          if [ -f requirements_dev.txt ]; then pip install -r requirements_dev.txt; fi
      - uses: chartboost/ruff-action@v1
      - name: Check formatting with Black
        run: |
          black . --check --verbose
      - name: Test with pytest
        run: |
          pytest --cov=emberwind tests/
        env:
          EMBERWIND_API_KEY: ${{ secrets.EMBERWIND_API_KEY }}
          EMBERWIND_TEST_EMAIL: ${{ secrets.EMBERWIND_TEST_EMAIL }}
          EMBERWIND_TEST_PASSWORD: ${{ secrets.EMBERWIND_TEST_PASSWORD }}
      - name: Coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          coveralls --service=github
  coveralls:
    name: Indicate completion to coveralls.io
    needs: test
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
    - name: Finished
      run: |
        pip3 install --upgrade coveralls
        coveralls --service=github --finish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
